document.addEventListener('DOMContentLoaded',()=>{
  const splitTitle=(title)=>{if(!title)return;title.classList.add('motion-title','motion-item');const walk=(node)=>{[...node.childNodes].forEach(child=>{if(child.nodeType===3){const words=child.textContent.split(/(\s+)/);const box=document.createDocumentFragment();words.forEach(word=>{if(/^\s+$/.test(word)){box.appendChild(document.createTextNode(word));}else if(word){const span=document.createElement('span');span.className='motion-word';span.textContent=word;box.appendChild(span);}});child.replaceWith(box)}else if(child.nodeType===1)walk(child)})};walk(title);title.querySelectorAll('.motion-word').forEach((word,index)=>word.style.setProperty('--word-delay',`${index*42}ms`));};
  document.querySelectorAll('.hero-copy h1,.page-title').forEach(splitTitle);
  const selectors=['.topbar','.hero-copy .eyebrow','.hero-copy strong','.hero-copy p','.hero-buttons','.hero-art','.stats .stat','.section-head','.section .project','.page>.kicker','.page>.lead','.page .card'];
  const items=[];selectors.forEach(selector=>document.querySelectorAll(selector).forEach((el,index)=>{if(!el.classList.contains('motion-item')){el.classList.add('motion-item');el.style.setProperty('--delay',`${(index%5)*90}ms`);items.push(el)}}));
  document.querySelectorAll('.motion-title').forEach(el=>items.push(el));
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -30px'});items.forEach(el=>observer.observe(el));
  const art=document.querySelector('.hero-art');if(art&&!matchMedia('(prefers-reduced-motion: reduce)').matches){art.addEventListener('pointermove',event=>{const rect=art.getBoundingClientRect();art.style.setProperty('--tilt-x',`${((event.clientX-rect.left)/rect.width-.5)*5}deg`);art.style.setProperty('--tilt-y',`${((event.clientY-rect.top)/rect.height-.5)*-4}deg`)});art.addEventListener('pointerleave',()=>{art.style.setProperty('--tilt-x','0deg');art.style.setProperty('--tilt-y','0deg')})}
});
