document.addEventListener('DOMContentLoaded',()=>{
  const page=location.pathname.split('/').pop()||'index.html';
  const set=(selector,html,all=false)=>{const nodes=document.querySelectorAll(selector);(all?nodes:[nodes[0]]).filter(Boolean).forEach(n=>n.innerHTML=html)};
  const linkedin='https://www.linkedin.com/in/faiz-ahmed-dev/';
  if(page==='index.html'){
    set('.hero-copy strong','Software Engineer at Setubo · Next.js, React & GraphQL');
    set('.hero-copy p','I build scalable, user-focused web applications with Next.js, TypeScript, React and GraphQL — with clean code and carefully considered UI/UX.');
    set('.stat:nth-child(1) b','2+'); set('.stat:nth-child(1) small','Years of experience');
    set('.stat:nth-child(2) b','Setubo'); set('.stat:nth-child(2) small','Software Engineer');
    set('.stat:nth-child(3) b','GraphQL · RBAC'); set('.stat:nth-child(3) small','Modern product systems');
    const cards=document.querySelectorAll('.projects .project');
    if(cards[0]){cards[0].querySelector('h3').textContent='GolfGuiders Admin Dashboard';cards[0].querySelector('p').textContent='A scalable Next.js control center for moderation, users, RBAC, menus, email templates and platform operations.';cards[0].querySelector('.tags').innerHTML='<span class="tag">Next.js</span><span class="tag">TypeScript</span><span class="tag">GraphQL</span><span class="tag">shadcn/ui</span>'}
    if(cards[1]){cards[1].querySelector('h3').textContent='Clamit Product Store';cards[1].querySelector('p').textContent='A responsive e-commerce store builder with secure authentication, live API data and reliable state management.';cards[1].querySelector('.tags').innerHTML='<span class="tag">Next.js</span><span class="tag">Redux</span><span class="tag">REST APIs</span>'}
  }
  if(page==='about.html'){
    set('.lead','I’m Faiz Ahmed, a Lahore-based Software Engineer at Setubo. I focus on building clean, scalable front-end applications with Next.js, TypeScript, React and GraphQL.');
    set('.card:first-of-type .lead','I turn complex product requirements into clear, maintainable interfaces. My work balances strong architecture, responsive UI and useful details that make operations easier for real teams.');
    const timeline=document.querySelector('.timeline');if(timeline)timeline.innerHTML='<div class="timeline-item"><b>Understand the workflow</b>Start with the users, business rules and the product’s real-world edge cases.</div><div class="timeline-item"><b>Build scalable interfaces</b>Create modular Next.js features with TypeScript, GraphQL and reusable UI.</div><div class="timeline-item"><b>Polish the experience</b>Refine responsiveness, accessibility, performance and interaction details.</div>';
  }
  if(page==='skills.html'){
    const cards=document.querySelectorAll('.card');if(cards[0])cards[0].innerHTML='<h3>Engineering stack</h3><div class="skill"><div class="skill-head"><span>Next.js / React</span><span>95%</span></div><div class="bar"><span style="width:95%"></span></div></div><div class="skill"><div class="skill-head"><span>TypeScript</span><span>90%</span></div><div class="bar"><span style="width:90%"></span></div></div><div class="skill"><div class="skill-head"><span>GraphQL / Apollo Client</span><span>88%</span></div><div class="bar"><span style="width:88%"></span></div></div>';
    if(cards[1])cards[1].innerHTML='<h3>Product UI</h3><div class="skill"><div class="skill-head"><span>Tailwind CSS / shadcn/ui</span><span>94%</span></div><div class="bar"><span style="width:94%"></span></div></div><div class="skill"><div class="skill-head"><span>Redux Toolkit</span><span>88%</span></div><div class="bar"><span style="width:88%"></span></div></div><div class="skill"><div class="skill-head"><span>REST API integration</span><span>90%</span></div><div class="bar"><span style="width:90%"></span></div></div>';
  }
  if(page==='projects.html'){
    const cards=document.querySelectorAll('.projects .project');
    if(cards[0]){cards[0].querySelector('h3').textContent='GolfGuiders Admin Dashboard';cards[0].querySelector('p').textContent='A full admin platform for user management, moderation, reporting, app menus, templates, versioning and role-based access.';cards[0].querySelector('.tags').innerHTML='<span class="tag">Next.js</span><span class="tag">GraphQL</span><span class="tag">RBAC</span><span class="tag">shadcn/ui</span>'}
    if(cards[1]){cards[1].querySelector('h3').textContent='Clamit Product Store';cards[1].querySelector('p').textContent='A responsive e-commerce store-builder frontend with authentication, API integration and Redux state management.';cards[1].querySelector('.tags').innerHTML='<span class="tag">Next.js</span><span class="tag">Redux</span><span class="tag">REST APIs</span>'}
  }
  if(page==='resume.html'){const cards=document.querySelectorAll('.card');if(cards[0])cards[0].innerHTML='<h3>Experience</h3><div class="timeline"><div class="timeline-item"><b>Software Engineer · Setubo</b>Jul 2025 — Present · Lahore<br>Building scalable Next.js applications, GraphQL integrations and role-based product workflows.</div><div class="timeline-item"><b>Next.js Frontend Developer · DevDock</b>Oct 2024 — Aug 2025<br>Developed polished, responsive web interfaces and API-connected product experiences.</div></div>';if(cards[1])cards[1].innerHTML='<h3>Education</h3><div class="timeline"><div class="timeline-item"><b>University of South Asia</b>2019 — 2023</div><div class="timeline-item"><b>Islamia College Lahore</b>2018 — 2019</div></div>'}
  if(page==='services.html'){const cards=document.querySelectorAll('.service-grid .card');if(cards[0])cards[0].querySelector('p').textContent='Scalable, production-ready Next.js and React applications built with maintainable TypeScript.';if(cards[1]){cards[1].querySelector('h3').textContent='Admin & product systems';cards[1].querySelector('p').textContent='Operational dashboards, RBAC flows and complex product UI that keeps teams in control.'}if(cards[2]){cards[2].querySelector('h3').textContent='API & state integration';cards[2].querySelector('p').textContent='GraphQL, REST APIs and Redux Toolkit integrations that keep live product data dependable.'}}
  if(page==='contact.html'){const items=document.querySelectorAll('.contact-item');if(items[0])items[0].innerHTML='<b>LinkedIn</b><a href="'+linkedin+'" target="_blank" rel="noreferrer">linkedin.com/in/faiz-ahmed-dev</a>';if(items[1])items[1].innerHTML='<b>Location</b>Lahore, Punjab, Pakistan';if(items[2])items[2].innerHTML='<b>Availability</b>Open to collaboration and product-focused frontend work>'}
  document.querySelectorAll('.socials').forEach(s=>s.innerHTML='<a href="'+linkedin+'" target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><span>◉</span><span>𝕏</span><span>◎</span>');
});
